pub fn render(shell: &str) -> Option<&'static str> {
    match shell {
        "zsh" => Some(ZSH),
        _ => None,
    }
}

pub fn supported() -> &'static [&'static str] {
    &["zsh"]
}

const ZSH: &str = r##"# cargoterm zsh integration
# Generated by `cargoterm init zsh`. Source it by adding to your ~/.zshrc:
#   eval "$(cargoterm init zsh)"

_cargoterm_current_enter() {
    bindkey -L '^M' 2>/dev/null | awk '{print $NF}'
}

cargoterm-on() {
    # Base the "is it on?" check on actual zsh state, not an env var. The
    # CARGOTERM_ACTIVE export survives `exec zsh`, but keybindings don't —
    # so after an exec, the var would be set but our widget wouldn't be
    # bound to ^M. Checking the binding is the source of truth.
    if [[ "$(_cargoterm_current_enter)" == "_cargoterm_accept_line" ]]; then
        echo "cargoterm: already ON"
        return
    fi
    CARGOTERM_ACTIVE=1
    _CARGOTERM_ORIG_PROMPT="$PROMPT"
    PROMPT="%B◉%b ${_CARGOTERM_ORIG_PROMPT}"
    _CARGOTERM_PREV_ENTER="$(_cargoterm_current_enter)"
    [[ -z "$_CARGOTERM_PREV_ENTER" ]] && _CARGOTERM_PREV_ENTER="accept-line"
    bindkey '^M' _cargoterm_accept_line
    echo "cargoterm: ON — type natural language, press Enter to translate, Enter again to run"
}

cargoterm-off() {
    if [[ "$(_cargoterm_current_enter)" != "_cargoterm_accept_line" ]]; then
        # Binding is not ours — clean up any stale state and report off.
        unset CARGOTERM_ACTIVE CARGOTERM_PENDING_CMD _CARGOTERM_PREV_ENTER _CARGOTERM_ORIG_PROMPT
        echo "cargoterm: already OFF"
        return
    fi
    unset CARGOTERM_ACTIVE CARGOTERM_PENDING_CMD
    bindkey '^M' "${_CARGOTERM_PREV_ENTER:-accept-line}"
    unset _CARGOTERM_PREV_ENTER
    if [[ -n "$_CARGOTERM_ORIG_PROMPT" ]]; then
        PROMPT="$_CARGOTERM_ORIG_PROMPT"
    fi
    unset _CARGOTERM_ORIG_PROMPT
    echo "cargoterm: OFF"
}

# Shared: translate the current BUFFER in place. Used by Ctrl+G always, and
# by the accept-line override while the mode is active.
_cargoterm_translate_buffer() {
    local input="$BUFFER"
    if [[ -z "$input" ]]; then
        zle -M "cargoterm: nothing to translate"
        return 1
    fi
    if ! command -v cargoterm >/dev/null 2>&1; then
        zle -M "cargoterm: binary not found on PATH"
        return 1
    fi
    local output exit_code
    output=$(cargoterm --translate "$input" 2>&1)
    exit_code=$?
    if (( exit_code != 0 )); then
        local msg="${output#cargoterm: }"
        msg="${msg%%$'\n'*}"
        zle -M "cargoterm: ${msg:-translation failed}"
        return 1
    fi
    local cmd="" explain="" line
    while IFS= read -r line; do
        case "$line" in
            cmd:\ *)     cmd="${line#cmd: }" ;;
            explain:\ *) explain="${line#explain: }" ;;
        esac
    done <<< "$output"
    if [[ -z "$cmd" ]]; then
        zle -M "cargoterm: model returned no command"
        return 1
    fi
    BUFFER="$cmd"
    CURSOR=${#BUFFER}
    CARGOTERM_PENDING_CMD="$cmd"
    if [[ -n "$explain" ]]; then
        zle -M "$explain — press Enter to run, Ctrl+U to cancel"
    else
        zle -M "press Enter to run, Ctrl+U to cancel"
    fi
    return 0
}

# Ctrl+G — always translate the current line, regardless of mode.
_cargoterm_translate_widget() {
    _cargoterm_translate_buffer
}
zle -N _cargoterm_translate_widget
bindkey '^G' _cargoterm_translate_widget

# Heuristic: does the current BUFFER look like a real command the user meant
# to run literally, or natural language that should go to the LLM?
# Prints nothing; returns 0 (passthrough) or 1 (translate).
_cargoterm_looks_like_command() {
    local first="${BUFFER%% *}"

    # cd and exit always pass through.
    [[ "$first" == "cd" || "$first" == "exit" ]] && return 0

    # Explicit path form.
    case "$first" in
        ./*|../*|/*|~*) return 0 ;;
    esac

    # Split tokens via zsh word-split; do not reuse $tokens (special array).
    local -a _toks
    _toks=(${=BUFFER})

    # If any argument looks like a flag, path, or assignment, this is a
    # command invocation, not English: e.g. `ls -la`, `cp a/b c`, `K=V cmd`.
    local tok
    for tok in "${_toks[@]:1}"; do
        case "$tok" in
            -*|*/*|*=*) return 0 ;;
        esac
    done

    # If the first word doesn't resolve to anything the shell recognises,
    # it's almost certainly English. Translate.
    (( ${+commands[$first]} || ${+functions[$first]} || ${+aliases[$first]} || ${+builtins[$first]} )) || return 1

    # Commands that routinely take plain-word arguments — passthrough.
    # Extend this list in your shell if you use others heavily:
    #   CARGOTERM_PASSTHROUGH_CMDS=(... custom tools ...)
    local -a known
    known=(
        git gh hg
        cargo rustup
        npm pnpm yarn
        pip uv poetry pipx
        brew apt dnf yum pacman
        docker podman kubectl helm
        make cmake bazel ninja
        ssh scp rsync curl wget
        ls cat cp mv mkdir rmdir touch ln head tail
        echo printf env
        tar zip unzip gunzip gzip
        vi vim nvim nano emacs code
        go python python3 ruby node deno bun
    )
    if (( ${#CARGOTERM_PASSTHROUGH_CMDS} )); then
        known+=("${CARGOTERM_PASSTHROUGH_CMDS[@]}")
    fi
    if (( ${known[(Ie)$first]} )); then
        return 0
    fi

    # Single-token, shell-resolvable → plain command like `ls`, `pwd`.
    (( ${#_toks[@]} == 1 )) && return 0

    # First word happens to be a command name (like `where`, `who`, `find`,
    # `cat`, `file`) but the rest reads as English. Translate.
    return 1
}

# Enter — smart accept: while mode is on, translate English input; pass
# real commands straight through; a second Enter press after a translation
# runs the rewritten command.
_cargoterm_accept_line() {
    # Mode off or empty buffer → normal accept
    if [[ -z "$CARGOTERM_ACTIVE" || -z "$BUFFER" ]]; then
        zle .accept-line
        return
    fi
    # Second Enter after a translation → run what's in the buffer
    if [[ -n "$CARGOTERM_PENDING_CMD" && "$BUFFER" == "$CARGOTERM_PENDING_CMD" ]]; then
        unset CARGOTERM_PENDING_CMD
        zle .accept-line
        return
    fi
    # Buffer changed since last translation — discard pending state
    unset CARGOTERM_PENDING_CMD

    if _cargoterm_looks_like_command; then
        zle .accept-line
        return
    fi

    # Natural language path — translate; widget shows message and leaves
    # the rewritten buffer for the user to confirm with a second Enter.
    _cargoterm_translate_buffer
}
zle -N _cargoterm_accept_line
"##;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn zsh_snippet_defines_expected_functions() {
        let snippet = render("zsh").unwrap();
        assert!(snippet.contains("cargoterm-on()"));
        assert!(snippet.contains("cargoterm-off()"));
        assert!(snippet.contains("_cargoterm_translate_widget"));
        assert!(snippet.contains("_cargoterm_accept_line"));
        assert!(snippet.contains("bindkey '^G'"));
    }

    #[test]
    fn zsh_snippet_rebinds_enter_in_cargoterm_on() {
        let snippet = render("zsh").unwrap();
        assert!(snippet.contains("bindkey '^M' _cargoterm_accept_line"));
        assert!(snippet.contains("_CARGOTERM_PREV_ENTER"));
    }

    #[test]
    fn zsh_snippet_passes_through_known_commands() {
        let snippet = render("zsh").unwrap();
        assert!(snippet.contains("${+commands[$first]}"));
        assert!(snippet.contains("${+functions[$first]}"));
        assert!(snippet.contains("${+aliases[$first]}"));
    }

    #[test]
    fn zsh_snippet_uses_double_enter_pattern() {
        let snippet = render("zsh").unwrap();
        assert!(snippet.contains("CARGOTERM_PENDING_CMD"));
    }

    #[test]
    fn zsh_snippet_has_refined_heuristic() {
        let snippet = render("zsh").unwrap();
        assert!(snippet.contains("_cargoterm_looks_like_command"));
        // Flag / path / assignment detection
        assert!(snippet.contains("-*|*/*|*=*"));
        // Explicit path prefixes
        assert!(snippet.contains("./*|../*|/*|~*"));
    }

    #[test]
    fn zsh_snippet_passthrough_whitelist_has_common_tools() {
        let snippet = render("zsh").unwrap();
        for tool in ["git", "cargo", "npm", "docker", "ssh", "ls", "echo"] {
            assert!(
                snippet.contains(&format!(" {tool} "))
                    || snippet.contains(&format!("{tool} "))
                    || snippet.contains(&format!(" {tool}\n"))
                    || snippet.contains(&format!("\n        {tool}")),
                "whitelist missing {tool}"
            );
        }
    }

    #[test]
    fn zsh_snippet_supports_user_passthrough_extension() {
        let snippet = render("zsh").unwrap();
        assert!(snippet.contains("CARGOTERM_PASSTHROUGH_CMDS"));
    }

    #[test]
    fn cargoterm_on_checks_binding_not_env_var() {
        // Key invariant: cargoterm-on must survive `exec zsh`, which
        // preserves env vars but resets keybindings. If the gate is only
        // on CARGOTERM_ACTIVE, cargoterm-on would falsely say "already ON"
        // after an exec and never re-apply the widget binding.
        let snippet = render("zsh").unwrap();
        assert!(snippet.contains("_cargoterm_current_enter"));
        assert!(snippet.contains("_cargoterm_accept_line\" ]]"));
    }

    #[test]
    fn zsh_snippet_marks_active_with_bold_indicator() {
        let snippet = render("zsh").unwrap();
        assert!(snippet.contains("%B"));
        assert!(snippet.contains("%b"));
    }

    #[test]
    fn zsh_snippet_calls_translate_flag() {
        let snippet = render("zsh").unwrap();
        assert!(snippet.contains("cargoterm --translate"));
    }

    #[test]
    fn unknown_shell_returns_none() {
        assert!(render("fish").is_none());
        assert!(render("pwsh").is_none());
    }
}
