pub fn render(shell: &str) -> Option<&'static str> {
    match shell {
        "zsh" => Some(ZSH),
        _ => None,
    }
}

pub fn supported() -> &'static [&'static str] {
    &["zsh"]
}

const ZSH: &str = r##"# cargoterm zsh integration
# Generated by `cargoterm init zsh`. Source it by adding to your ~/.zshrc:
#   eval "$(cargoterm init zsh)"

cargoterm-on() {
    if [[ -n "$CARGOTERM_ACTIVE" ]]; then
        echo "cargoterm: already ON"
        return
    fi
    export CARGOTERM_ACTIVE=1
    _CARGOTERM_ORIG_PROMPT="$PROMPT"
    PROMPT="%B◉%b ${_CARGOTERM_ORIG_PROMPT}"
    echo "cargoterm: ON — press Ctrl+G to translate the current line"
}

cargoterm-off() {
    if [[ -z "$CARGOTERM_ACTIVE" ]]; then
        echo "cargoterm: already OFF"
        return
    fi
    unset CARGOTERM_ACTIVE
    if [[ -n "$_CARGOTERM_ORIG_PROMPT" ]]; then
        PROMPT="$_CARGOTERM_ORIG_PROMPT"
    fi
    unset _CARGOTERM_ORIG_PROMPT
    echo "cargoterm: OFF"
}

_cargoterm_translate_widget() {
    local input="$BUFFER"
    if [[ -z "$input" ]]; then
        zle -M "cargoterm: nothing to translate"
        return
    fi
    if ! command -v cargoterm >/dev/null 2>&1; then
        zle -M "cargoterm: binary not found on PATH"
        return
    fi
    local output
    output=$(cargoterm --translate "$input" 2>/dev/null)
    if [[ $? -ne 0 || -z "$output" ]]; then
        zle -M "cargoterm: translation failed (is ollama running?)"
        return
    fi
    local cmd=""
    local explain=""
    local line
    while IFS= read -r line; do
        case "$line" in
            cmd:\ *)     cmd="${line#cmd: }" ;;
            explain:\ *) explain="${line#explain: }" ;;
        esac
    done <<< "$output"
    if [[ -n "$cmd" ]]; then
        BUFFER="$cmd"
        CURSOR=${#BUFFER}
        if [[ -n "$explain" ]]; then
            zle -M "$explain"
        fi
    else
        zle -M "cargoterm: model returned no command"
    fi
}
zle -N _cargoterm_translate_widget
bindkey '^G' _cargoterm_translate_widget
"##;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn zsh_snippet_defines_expected_functions() {
        let snippet = render("zsh").unwrap();
        assert!(snippet.contains("cargoterm-on()"));
        assert!(snippet.contains("cargoterm-off()"));
        assert!(snippet.contains("_cargoterm_translate_widget"));
        assert!(snippet.contains("bindkey '^G'"));
    }

    #[test]
    fn zsh_snippet_marks_active_with_bold_indicator() {
        let snippet = render("zsh").unwrap();
        assert!(snippet.contains("%B"));
        assert!(snippet.contains("%b"));
    }

    #[test]
    fn zsh_snippet_calls_translate_flag() {
        let snippet = render("zsh").unwrap();
        assert!(snippet.contains("cargoterm --translate"));
    }

    #[test]
    fn unknown_shell_returns_none() {
        assert!(render("fish").is_none());
        assert!(render("pwsh").is_none());
    }
}
